### PR TITLE
Fix some code examples

### PR DESCRIPTION
**Pull request by mattsches**
Signed-off-by: Matthias Gutjahr <mattsches@gmail.com>

### CODE REVIEW

**Comment by mmoreram** [comment]
@mattsches I'm not really sure about the changes on this PR.
The commit diff seems to expose "the old document" for "the new document" as a block, instead of showing the changed lines :S

**Comment by mattsches** [comment]
Strange, my local diff is fine. I will try to edit and resubmit the PR.

**Comment by mattsches** [comment]
Just found out, you can click on the "Rich diff" button in the "Files changed" view here on GitHub. There you can see a better preview of what's changed.

**Comment by mmoreram** [comment]
¬¬

It was my Github diff view configuration.
Sorry, dude.

**Comment by mmoreram** [comment]
Amazing, thanks for that review :D

**Pull request merged**
